### PR TITLE
chore(ci): Use latest `pr-title.yml` from `hugrverse-actions`

### PR DESCRIPTION
**Pull request by aborgna-q**
The `hugrverse-actions` provides a single source of truth for shared workflows between repos, so it's easier to distribute any fixes.

https://github.com/CQCL/hugrverse-actions?tab=readme-ov-file#pr-title

### CODE REVIEW

**Comment by aborgna-q** [comment]
Flaky CI, or did something break with the move to open source?
https://github.com/CQCL/qnexus/actions/runs/11291759987/job/31406360620?pr=105#step:7:25

**Comment by vanyae-cqc** [comment]
I think I just need to get @johnchildren to set up autoassigning reviewers from the team: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team

**Comment by vanyae-cqc** [comment]
@aborgna-q is this a PR from a fork? For some reason it looks like the CI isn't loading the github secret environment variables to authenticate the integration test user

**Comment by aborgna-q** [comment]
Ah, right. I don't have access to this repo, so I pushed from a fork.

PRs with external sources don't get access to private secrets (asides from GITHUB_TOKEN), as that would be a security issue since the PR can modify the workflow being run.

There is no good solution for that, either
- Change the workflow trigger to a `pull_request_target` one so it reads the `.yml` from the base branch. This makes updating and testing the workflow more annoying.
- Disable the check for external forks 🤷

**Review by vanyae-cqc — APPROVED** [review]
Thanks for your patience @aborgna-q !

**Pull request merged**
